### ISSUE TITLE
Add some variables into DB

### ISSUE THREAD

**Issue by tintamarre** [openjusticebe/data_api#2]
## Current insert query 
    sql = """
    INSERT INTO ecli_document (
        ecli,
        country,
        court,
        year,
        identifier,
        text,
        meta,
        ukey,
        hash
    ) VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9);
    """
Source https://github.com/openjusticebe/data_api/blob/master/data_api/main.py#L121

## Proposition to include 
- `updated_at`: Datetime
- `created_at`: Datetime
- `language`: `fr|nl|de` (it could of course be in meta but i think if it is better to include separatly )

**Comment by PieterjanMontens** [comment]
Update and created fields do exist (set by default for created ts) :
```
CREATE TABLE "ecli_document" (
    id_internal SERIAL PRIMARY KEY,
    hash TEXT,
    ecli TEXT,
    country VARCHAR(2),
    court TEXT,
    year INT,
    identifier TEXT,
    text TEXT,
    meta JSONB,
    flags TEXT[],
    ukey TEXT,
    date_created TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date_updated TIMESTAMP WITH TIME ZONE
);
```
Adding language !

**Comment by PieterjanMontens** [comment]
Done in https://github.com/openjusticebe/data_api/pull/3

**Comment by tintamarre** [comment]
Flags ? Flags is mostly used to define a country not a language. Language is defined by the iso639(1 or 2). Don't you think it is better to use something other than flags ?

**Comment by PieterjanMontens** [comment]
:thinking:  `tags` ? but in a technical sense. Can also be replace by `attributes`

**Comment by PieterjanMontens** [comment]
- added Status enum ('new', 'public', 'hidden', 'flagged', 'deleted', 'boosted')
- added language varchar 2

**Comment by tintamarre** [comment]
Language is perfect. 👍
